-- JNE App 1.7.3 — interface administrativa e métricas próprias do site.
-- Migration segura para bancos já em uso.

create table if not exists public.site_page_views (
  id bigint generated by default as identity primary key,
  path text not null check (path like '/%' and char_length(path) <= 180),
  visitor_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists site_page_views_created_at_idx
  on public.site_page_views(created_at desc);

create index if not exists site_page_views_path_created_at_idx
  on public.site_page_views(path, created_at desc);

create index if not exists site_page_views_visitor_created_at_idx
  on public.site_page_views(visitor_hash, created_at desc);

alter table public.site_page_views enable row level security;
revoke all on public.site_page_views from public, anon, authenticated;

create or replace function public.admin_site_traffic_daily(days_count integer default 30)
returns table (
  day date,
  page_views bigint,
  unique_visitors bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_days integer := greatest(1, least(coalesce(days_count, 30), 90));
begin
  if not public.is_admin() then
    raise exception 'Acesso administrativo necessário.' using errcode = '42501';
  end if;

  return query
  with calendar as (
    select generate_series(
      (now() at time zone 'America/Sao_Paulo')::date - (safe_days - 1),
      (now() at time zone 'America/Sao_Paulo')::date,
      interval '1 day'
    )::date as metric_day
  )
  select
    calendar.metric_day,
    count(view_item.id)::bigint,
    count(distinct view_item.visitor_hash)::bigint
  from calendar
  left join public.site_page_views view_item
    on (view_item.created_at at time zone 'America/Sao_Paulo')::date = calendar.metric_day
  group by calendar.metric_day
  order by calendar.metric_day;
end;
$$;

create or replace function public.admin_site_traffic_summary(days_count integer default 30)
returns table (
  page_views bigint,
  unique_visitors bigint,
  views_today bigint,
  visitors_today bigint,
  previous_period_views bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_days integer := greatest(1, least(coalesce(days_count, 30), 90));
  today_date date := (now() at time zone 'America/Sao_Paulo')::date;
begin
  if not public.is_admin() then
    raise exception 'Acesso administrativo necessário.' using errcode = '42501';
  end if;

  return query
  select
    count(*) filter (
      where (created_at at time zone 'America/Sao_Paulo')::date >= today_date - (safe_days - 1)
    )::bigint,
    count(distinct visitor_hash) filter (
      where (created_at at time zone 'America/Sao_Paulo')::date >= today_date - (safe_days - 1)
    )::bigint,
    count(*) filter (
      where (created_at at time zone 'America/Sao_Paulo')::date = today_date
    )::bigint,
    count(distinct visitor_hash) filter (
      where (created_at at time zone 'America/Sao_Paulo')::date = today_date
    )::bigint,
    count(*) filter (
      where (created_at at time zone 'America/Sao_Paulo')::date between today_date - ((safe_days * 2) - 1) and today_date - safe_days
    )::bigint
  from public.site_page_views;
end;
$$;

create or replace function public.admin_site_top_pages(days_count integer default 30, result_limit integer default 10)
returns table (
  path text,
  page_views bigint,
  unique_visitors bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_days integer := greatest(1, least(coalesce(days_count, 30), 90));
  safe_limit integer := greatest(1, least(coalesce(result_limit, 10), 50));
  today_date date := (now() at time zone 'America/Sao_Paulo')::date;
begin
  if not public.is_admin() then
    raise exception 'Acesso administrativo necessário.' using errcode = '42501';
  end if;

  return query
  select
    view_item.path,
    count(*)::bigint,
    count(distinct view_item.visitor_hash)::bigint
  from public.site_page_views view_item
  where (view_item.created_at at time zone 'America/Sao_Paulo')::date >= today_date - (safe_days - 1)
  group by view_item.path
  order by count(*) desc, view_item.path
  limit safe_limit;
end;
$$;

revoke all on function public.admin_site_traffic_daily(integer) from public, anon;
revoke all on function public.admin_site_traffic_summary(integer) from public, anon;
revoke all on function public.admin_site_top_pages(integer, integer) from public, anon;

grant execute on function public.admin_site_traffic_daily(integer) to authenticated;
grant execute on function public.admin_site_traffic_summary(integer) to authenticated;
grant execute on function public.admin_site_top_pages(integer, integer) to authenticated;
